config/routes.rb
Rails.application.routes.draw do

  devise_for :players

  resources :players do
    resources :bags
  end

  resources :bags
  resources :drugs

  root to: "static_pages#home"

  get 'static_pages/home', to: "static_pages#home"

  get 'static_pages/about'

end

app/models/bag.rb
class Bag < ActiveRecord::Base
  belongs_to :player
  has_many :drugs, through: :player
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :drugs
end

app/models/drug.rb
class Drug < ActiveRecord::Base

  def randomselection(array_of_drugs)
    random_number = rand(4..array_of_drugs.length)
    array_of_drugs.sample(random_number)
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bags
  has_many :weapons
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  def index
    @bags = Bag.where(player_id: params[:player_id])
  end

  def show
    @bag = Bag.where(player_id: params[:player_id]).first
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def index
    @drugs = Drug.all
  end

  def show
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
    @drugs = Drug.all
  end

  def show
    @player = Player.find(params[:id])
    @drugs = Drug.all
    # @bag = Bag.where(player_id: @player.id).first
  end

  def new
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    @player.update(params_player)
    redirect_to player_path
  end

  def destroy
  end

  private

  def params_player
    params.require(:player).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bags/destroy.html.erb
<h1>Bags#destroy</h1>
<p>Find me in app/views/bag/destroy.html.erb</p>

app/views/bags/edit.html.erb
<h1>Bags#edit</h1>
<p>Find me in app/views/bag/edit.html.erb</p>

app/views/bags/new.html.erb
<h1>Bags#new</h1>
<p>Find me in app/views/bag/new.html.erb</p>

app/views/bags/show.html.erb
<h1>Bags#show</h1>
<p>Find me in app/views/bag/show.html.erb</p>

app/views/drugs/index.html.erb
<div class="container">
  <div class="row text-center">
    <h3>Here's what drugs are selling for:</h3>
    <hr>
    <ul class="list-unstyled">
      <% @drugs.each do |drug| %>
        <li><%= drug.name %> @ $<%= drug.price %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/drugs/show.html.erb
<h1>Drugs#show</h1>
<p>Find me in app/views/drugs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playdrugwars</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link href='https://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>



</head>
<body>
<%= render 'shared/navbar' %>
<%= yield %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<%= simple_form_for @player do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/players/index.html.erb
<%= link_to "Bobby", player_path(1) %>

<%#= link_to "See your profile", player_path(current_player) %>
<ul class="list-unstyled">
  <% @drugs.each do |drug| %>
    <li><%= drug.name %> is selling for $<%= drug.price %></li>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1>Players#new</h1>
<p>Find me in app/views/players/new.html.erb</p>

app/views/players/show.html.erb
<div class="container text-center">
  <h1>Hey <%= @player.name %></h1>
  <div class="row">

    <div class="col-md-4">
    <% if false %>
      <h3>Your bag has <strong><%= @bag.space %></strong> slots right now.</h3>
    <% end %>
      <hr>
    </div>

    <div class="col-md-4">
      <h3>Here's what drugs are selling for:</h3>
      <hr>
      <ul class="list-unstyled">
        <% @drugs.each do |drug| %>
          <li><%= drug.name %> @ $<%= drug.price %></li>
        <% end %>
      </ul>
      <% if false %>
      <%= simple_form_for @drugs  do |f| %>
        <%= f.input :name %>
        <%= f.button :submit %>
      <% end %>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>Here are your stats:</h3>
      <hr>
      <ul class="list-unstyled">
        <% if @player.health == nil %>
          <li>Looks like you died!</li>
        <% else %>
          <li>Health: <%= @player.health %></li>
        <% end %>
        <% if @player.health == nil %>
          <li>Looks like you're broke!</li>
        <% else %>
          <li>Cash: <%= @player.cash %></li>
        <% end %>

        <% if @player.health == nil %>
          <li>Looks like you're really weak!</li>
        <% else %>
          <li>Strength: <%= @player.strength %></li>
        <% end %>
          <!-- <li>Debt: <%#= @loanshark.money_owned %></li> -->
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dope Wars", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%#= link_to "Your profile", current_player %></li>
        <li><%= link_to "Drugs", drugs_path %></li>
      </ul>
<% if false %>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_player %>
          <li><%= link_to "Sign up", new_player_registration_path %></li>
          <li><%= link_to "Sign in", new_player_session_path %></li>
        <% end %>
        <% if current_player %>
          <li class="nav navbar-text">Logged in as <%= current_player.name %></li>
          <li><%= link_to "Log out", destroy_player_session_path, method: :delete %></li>
        <% end %>
      </ul>
<% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row dashboard">

    <div id="stats" class="dashboard">
      <h3>Stats</h3>
      <h4>Cash</h4>
      <h4>Guns</h4>
      <h4>Health</h4>
      <h4>Bank</h4>
    </div>

    <div id="drugs" class="dashboard">
      <h3>Drugs</h3>
    </div>
  </div>

  <div class="row">
    <div id="game" class="dashboard">
      <h3>Game</h3>
    </div>
  </div>
</div>






<% if false %>
<div class="container flexbox">
  <div class="row text-center flexbox">
    <h1 class="font-war big-font" style="font-size: 100px"></h1>
    <!-- <h4 class="font-war">A WAR IS COMING...</h4> -->
  </div>
</div>


<script>
  $(function(){
      $(".font-war").typed({
        strings: ["Welcome to Drug Wars", "A WAR IS COMING."],
        typeSpeed: 80,
        backSpeed: 0,
      });
  });
</script>
<% end %>